#! /bin/sh
#
# reassume md devices

### BEGIN INIT INFO
# Provides:          jw-mdassume
# Required-Start:    jw-driver
# Required-Stop:
# Default-Start:     2
# Default-Stop:      0 1 6
# Short-Description: drivers for jwele
# Description:       same with above.
### END INIT INFO

. /usr/local/lib/jw-functions

export "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

_usage()
{
	echo "Usage: $(basename "$0")  {start}"
}

start_scst()
{
	modprobe scst
	modprobe scst_vdisk
	modprobe iscsi-scst
	iscsi-scstd
	if [ $? -eq 0 ]; then
		sys-manager iscsi --misc --restore-cfg
	fi
}

start_nas()
{
	/opt/jw-conf/nas/self-load.sh
}

case "${1:-}" in
	start)
		/usr/local/bin/md-assume.sh
		start_scst
		start_nas
	;;
	*)
		_usage
	;;
esac

exit 0
