#! /bin/sh
#
# reassume md devices

### BEGIN INIT INFO
# Provides:          jw-assemble
# Required-Start:    jw-apps
# Required-Stop:
# Default-Start:     2
# Default-Stop:      0 1 6
# Short-Description: drivers for jwele
# Description:       same with above.
### END INIT INFO

. /usr/local/lib/jw-functions

export "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

_usage()
{
	echo "Usage: $(basename "$0")  {start}"
}

start_md()
{
	/usr/local/bin/md-assume.sh
	#sys-manager vg --misc --restore
}

start_scst()
{
	modprobe scst
	modprobe scst_vdisk
	modprobe iscsi-scst
	iscsi-scstd
	if [ $? -eq 0 ]; then
		sys-manager iscsi --misc --restore-cfg | awk -F':' '{ print $NF }' | sed 's/^ //'| tr -d '}"!'
	fi
}

start_nas()
{
	sys-manager nas --misc --restore-cfg | awk -F':' '{ print $NF }' | sed 's/^ //' | tr -d '}"!'
}

case "${1:-}" in
	start)
		start_md
		start_scst
		start_nas
	;;
	stop)
		echo ""
	;;
	*)
		_usage
	;;
esac

exit 0
