#! /bin/sh
### BEGIN INIT INFO
# Provides:             jw-buzzer
# Required-Start:
# Required-Stop:
# Default-Start:        2
# Default-Stop:         0 1 6
# Short-Description:    jw buzzer
# Description:          buzzer ctl daemon
### END INIT INFO

export "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

LED_DAEMON="/usr/local/bin/buzzer-ctl-daemon"
LED_PID="/var/run/buzzer-ctl-daemon.pid"

. /lib/lsb/init-functions

__start_daemon()
{
	local _pid="$1"
	local _cmd="$2"

	start-stop-daemon --make-pidfile --pidfile $_pid --background --start \
		--exec $_cmd
	[ $? -eq 0 ] && echo "$(basename "$_cmd") started." && return
	echo "$(basename "$_cmd") start fail! retcode: $?"
}

do_start()
{
	__start_daemon $LED_PID $LED_DAEMON
}

do_stop()
{
	killproc -p $LED_PID $(basename $LED_DAEMON)
}

do_status()
{
	status_of_proc -p $LED_PID $LED_DAEMON $(basename $LED_DAEMON) $(basename $LED_DAEMON)
}

apps_usage()
{
	echo "Usage: $(basename "$0") {start|stop|restart|status}"
}

case "${1:-}" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		do_status
		;;
	*)
		apps_usage
		;;
esac
exit 0

