#! /bin/sh
#
# start/stop iSCSI Target.

### BEGIN INIT INFO
# Provides:          jw-driver
# Required-Start:    
# Required-Stop:
# Default-Start:     2
# Default-Stop:      0 1 6
# Short-Description: drivers for jwele
# Description:       same with above.
### END INIT INFO

export "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

do_driver_start()
{
	modprobe nct6106
	modprobe smbus-power
}

do_driver_stop()
{
	rmmod nct6106
	rmmod smbus-power
}

driver_usage()
{
	echo "Usage: $(basename "$0")  {start|stop|restart}"
}


case "${1:-}" in
	start)
		do_driver_start
	;;
	stop)
		do_driver_stop
	;;
	restart)
		do_driver_stop
		do_driver_start
	;;
	*)
		driver_usage
	;;
esac

exit 0
