#! /bin/sh
#
# start/stop iSCSI Target.

### BEGIN INIT INFO
# Provides:          jw-driver
# Required-Start:    
# Required-Stop:
# Default-Start:     2
# Default-Stop:      0 1 6
# Short-Description: drivers for jwele
# Description:       same with above.
### END INIT INFO

export "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

do_driver_start()
{
	modprobe i2c-i801
	modprobe i2c-dev
	sys_dir=`ls -d /sys/module/i2c_i801/drivers/pci\:i801_smbus/0000\:00\:*/i2c-* 2>/dev/null`
	i2c_node=`basename $sys_dir`
	if [ "$i2c_node" != "" ]; then
		cd /dev
		ln -sfn $i2c_node i2c-i801
		cd - >/dev/null
	fi

	modprobe nct6106
	make -p /opt/jw-conf/system
	if [ `hwtype` = "2U8-ATOM" ]; then
		ln -sfn /sys/devices/platform/nct6106.656/temp19_input /opt/jw-conf/system/temp_cpu
	else
		ln -sfn /sys/devices/platform/nct6106.656/temp17_input /opt/jw-conf/system/temp_cpu
	fi
	
	if [ `hwtype` = "3U16-STANDARD" ]; then
		modprobe smbus-power
	fi
	modprobe sio_watchdog
	
	if [ `hwtype` = "3U16-SIMPLE" ]; then
		for i in `seq 4`
		do
			diskpower-ctl -c $i -m on
			if [ $i -lt 4 ]; then
				sleep 1
			fi
		done
	fi
}

do_driver_stop()
{
	:
}

driver_usage()
{
	echo "Usage: $(basename "$0")  {start|stop}"
}


case "${1:-}" in
	start)
		do_driver_start
	;;
	stop)
		do_driver_stop
	;;
	*)
		driver_usage
	;;
esac

exit 0
