#! /bin/sh
#
# reassume md devices

### BEGIN INIT INFO
# Provides:          jw-mdassume
# Required-Start:    jw-driver
# Required-Stop:
# Default-Start:     2
# Default-Stop:      0 1 6
# Short-Description: drivers for jwele
# Description:       same with above.
### END INIT INFO


export "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

_usage()
{
	echo "Usage: $(basename "$0")  {start}"
}

case "${1:-}" in
	start)
		/usr/local/bin/md-assume.sh
		sys-manager iscsi --misc --check-default-target
		sys-manager iscsi --misc --update-cfg
		/etc/init.d/scst start
	;;
	*)
		_usage
	;;
esac

exit 0
