#! /bin/sh
#
# reassume md devices

### BEGIN INIT INFO
# Provides:          jw-mdassume
# Required-Start:    jw-driver
# Required-Stop:
# Default-Start:     2
# Default-Stop:      0 1 6
# Short-Description: drivers for jwele
# Description:       same with above.
### END INIT INFO

. /usr/local/lib/jw-functions

export "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

_usage()
{
	echo "Usage: $(basename "$0")  {start}"
}

start_scst()
{
	safe_exec modprobe scst
	safe_exec modprobe scst_vdisk
	safe_exec modprobe iscsi-scst
	safe_exec scstadmin -config $SCST_CFG
	[ $? -eq 0 ] && sys-manager iscsi --misc --update-cfg
}

case "${1:-}" in
	start)
		/usr/local/bin/md-assume.sh
		sys-manager iscsi --misc --check-default-target
		#/etc/init.d/scst start
		start_scst
	;;
	*)
		_usage
	;;
esac

exit 0
