#! /bin/sh
#
# start/stop iSCSI Target.

### BEGIN INIT INFO
# Provides:          jw-md-assume
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2
# Default-Stop:      0 1 6
# Short-Description: apps for jwele
# Description:       same with above.
### END INIT INFO

export "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

_usage()
{
	echo "Usage: $(basename "$0")  {start}"
}


case "${1:-}" in
	start)
		/usr/local/bin/md-assume.sh
	;;
	*)
		_usage
	;;
esac

exit 0
