#! /bin/sh
### BEGIN INIT INFO
# Provides:          jw-sysmon
# Required-Start:    jw-log
# Required-Stop:     jw-us
# Default-Start:     2
# Default-Stop:      0 1 6
# Short-Description: jw sysmon
# Description:       same with above.
### END INIT INFO

export "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

SYS_DAEMON="/usr/local/bin/sys-mon"

SYS_PID="/var/run/sys-mon.pid"

. /lib/lsb/init-functions

__start_daemon()
{
	local _pid="$1"
	local _cmd="$2"

	start-stop-daemon --make-pidfile --pidfile $_pid --background --start --exec $_cmd
	[ $? -eq 0 ] && echo "$(basename "$_cmd") started." && return
	echo "$(basename "$_cmd") start fail! retcode: $?"
}

do_start()
{
	__start_daemon $SYS_PID $SYS_DAEMON
}

do_stop()
{
	killproc -p $SYS_PID $(basename $SYS_DAEMON)
}

do_status()
{
	status_of_proc -p $SYS_PID $SYS_DAEMON $(basename $SYS_DAEMON) $(basename $SYS_DAEMON)
}

apps_usage()
{
	echo "Usage: $(basename "$0")  {start|stop|restart|status}"
}

case "${1:-}" in
	start)
		do_start
	;;
	stop)
		do_stop
	;;
	restart)
		$0 stop
		$0 start
	;;
	status)
		do_status
	;;
	*)
		apps_usage
	;;
esac

exit 0
