#!/usr/bin/env python

import sys

def main():
    if len(sys.argv) < 2:
        action = "Unknown"
    else:
        action = argv[1]
    print "%s called, action: %s" % (sys.argv[0], sys.argv[1])

if __name__ == "__main__":
    main()

        
