#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from libmd import *

def handle_md_rsync_complished(mddev):
	mdinfo = mddev_get_attr(mddev)
	if mdinfo['raid_state'] == 'normal':
		LogInsert('VG', 'Auto', 'Info', '卷组 %s 初始化完成！' % mdinfo['name'])
	return

# args [0]  - self
#      [1]  - dev eg. /dev/md1
#      [2]  - action 'add', 'remove', 'change'

def main():
	if len(sys.argv) < 3:
		return

	log = initlog()

	action = sys.argv[2]
	mddev = sys.argv[1]

	log.info('action: %s, mddev: %s' % (action, mddev))
	if 'add' == action:
		tmpfs_add_md_info(mddev)
	elif 'remove' == action:
		tmpfs_remove_md_info(mddev)
	elif 'change' == action:
		handle_md_rsync_complished(mddev)

if __name__ == "__main__":
	#  此程序调试通过，暂时不使用，因为在创建md时候，
	#  会首先收到add事件，但是此时取不到md信息
	#  已经将响应创建md事件加入到了md_create()函数最后
	# 将响应删除md事件加入到了md_del()函数最后
	main()
