#!/usr/bin/env python

import sys

def main():
    if len(sys.argv) < 3:
        action = "Unknown"
    else:
        action = sys.argv[2]
    print "%s called, action: %s" % (sys.argv[1], action)

if __name__ == "__main__":
    main()
        
