#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, commands
import us_disk, us_md
from libcommon import *


def main(argv):
    if (len(argv) < 2):
        return usage()
    cmd = argv[1]
    if cmd == "disk":
        return us_disk.disk_main(argv[1:])
    elif cmd == "vg":
        return us_md.main(argv[1:])
    return usage()

def usage():
    help_str="""
Usage:
        disk [disk参数]
        vg [卷参数]
"""
    return False,help_str

if __name__ == "__main__":
    res = main(sys.argv)
    debug_status(res)
