#!/bin/sh -x

do_set()
{
	IP=`ifconfig $NIC | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1`
	if [ -z "$IP" ]; then
		continue
	fi
	
	ip_segment=`ip route list table main proto kernel | grep "$NIC" | cut -d ' ' -f 1 | head -n 1`
	ip rule del table $NIC
	ip route add $ip_segment dev $NIC src $IP table $NIC
	ip rule add from $IP table $NIC
}

if [ "$1" = "auto" ]; then
	NICs=`ls /sys/class/net | grep eth`
	for NIC in $NICs
	do
		do_set
	done
	exit
fi

if [ ! -z "$1" ]; then
	NIC=$1
	do_set
	exit
fi
