#include "web-iface.h"
#include "common.h"

/******************************************************************************/
/* !!! DO NOT MODIFY BELOW LINES, THIS SHOWLE BE GENERATED BY version-info.sh */
/******************************************************************************/

#define HOST "lyt-pc"
#define IPADDR
#define GIT_BRANCH
#define GIT_COMMID
#define DATETIME

/******************************************************************************/
/* !!! DO NOT MODIFY ABOVE LINES, THIS SHOWLE BE GENERATED BY version-info.sh */
/******************************************************************************/

int version_main(int argc, char *argv[])
{
	// avoid compile warning
	argc = argc; argv = argv;

	printf("  System: %s(%s)\n", HOST, IPADDR);
	printf("  Version: GIT %s branch, commit id %s\n", GIT_BRANCH, GIT_COMMID);
	printf("  Build Date: %s\n", DATETIME);

	return 0;
}
