#include "web-iface.h"
#include "common.h"

/******************************************************************************/
/* !!! DO NOT MODIFY BELOW LINES, THIS SHOWLE BE GENERATED BY version-info.sh */
/******************************************************************************/

#define VERSION
#define HOST
#define IPADDR
#define GIT_BRANCH
#define GIT_COMMID
#define DATETIME

/******************************************************************************/
/* !!! DO NOT MODIFY ABOVE LINES, THIS SHOWLE BE GENERATED BY version-info.sh */
/******************************************************************************/

int version_main(int argc, char *argv[])
{
	// avoid compile warning
	argc = argc; argv = argv;

	printf("Version: %s\n", VERSION);
	if (argc >= 2 && 
		(strcmp(argv[1], "--detail") == 0 ||
		strcmp(argv[1], "-d") == 0)) {
		printf("System: %s(%s)\n", HOST, IPADDR);
		printf("GIT branch: %s\n", GIT_BRANCH);
		printf("GIT commit id: %s\n", GIT_COMMID);
		printf("Build Date: %s\n", DATETIME);
	}

	return 0;
}
